title: <p align="center"> Aswanth Varatharajan </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="www.linkedin.com/in/aswanth-varatharajan-2a9879b8/">LinkedIn</a> |
  <a href="https://github.com/AswanthVaratharajan">GitHub</a>
